name: Publish
on:
    release:
        types: [created]
    push:
        branches: [master]
jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'npm'
                  registry-url: '@gesund-ai:https://npm.pkg.github.com/'                  
            - run: npm install
            - run: npm run build
            # - run: |
            #       echo @gesund-ai:https://npm.pkg.github.com/ > build/.npmrc
            #       echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> build/.npmrc

            - uses: actions/setup-node@v3
              with:
                node-version: '16.x'
                registry-url: '@gesund-ai:https://npm.pkg.github.com/'

            - run: npm publish
              working-directory: .
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
